import type { Party } from "@prisma/client";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { NextRouter, useRouter } from "next/router";
import { trpc } from "../utils/trpc"

type CardProps = {
  name: string;
  link: string;
  router: NextRouter;
};

const Home: NextPage = () => {
  const partyQuery = trpc.useQuery(["getParties"])
  let party = new Array<Party>()
  if (partyQuery.data) {
    party = partyQuery.data
  }

  const router = useRouter()
  return (
    <>
      <Head>
        <title>Game Tools</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <h1 className="text-5xl md:text-[5rem] leading-normal font-extrabold text-green-600">
          Game Tools
        </h1>
        <div className="grid gap-3 pt-3 mt-3 text-center md:grid-cols-2 lg:w-2/3">
          {party.map(p => {
            return (
              <Card
                name={p.name}
                link={`/game/${p.id}`}
                router={router}
              />
            )
          })}
        </div>
        <div className="text-3xl rounded-md bg-green-700 px-6 py-2 mt-10">
          <Link href="/game/new">+</Link>
        </div>
      </main>
    </>
  );
};

const Card = ({
  name,
  link,
  router,
}: CardProps) => {
  return (
    <section
      onClick={() => router.push(link)}
      className="flex flex-col justify-center p-6 duration-500 border-2 border-green-500 rounded shadow-xl motion-safe:hover:scale-105 cursor-pointer">
      <h2 className="text-3xl text-green-700">{name}</h2>
    </section>
  );
};

export default Home;
